name: Production Build

on:
  push:
    branches:
      - production

env:
  PYTHON_VERSION: "3.12"
  APP_FILE: "app.py"
  APP_NAME: "Hello World Project"
  IMAGE_NAME: "merur1/hello-world-image"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Bump Version
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Check Docker
        run: docker --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Display Project Name
        run: echo "Building ${{ env.APP_NAME }}"

      - name: Run Application
        run: python ${{ env.APP_FILE }}

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.new_tag }} .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.new_tag }}

      - name: Show Docker Images
        run: docker images

      - name: Display New Version
        run: echo "New Docker Image Version = ${{ steps.version.outputs.new_tag }}"
